### ISSUE TITLE
Settings "Ligatures" and "Heading Bold" don't work

### ISSUE THREAD

**Issue by hungsu** [hungsu/typomagical-obsidian#16]
https://forum.obsidian.md/t/typomagical-a-theme-for-typographic-appreciators/26860/21?u=hungsu

**Comment by acorazza** [comment]
This is Sandro from the forums - happy to help if I can!

**Comment by hungsu** [comment]
Thanks @acorazza ! Could you update the theme on your end and check if the settings work for you now?

**Comment by acorazza** [comment]
✅ Bold headings work
✅ Ligatures work

Thank you for the quick fix, and for the theme!
