### ISSUE TITLE
Add bullet point relationship lines as a style option

### ISSUE THREAD

**Issue by hungsu** [hungsu/typomagical-obsidian#17]
https://forum.obsidian.md/t/typomagical-a-theme-for-typographic-appreciators/26860/22?u=hungsu

**Comment by hungsu** [comment]
This plugin does the same. https://github.com/mgmeyers/obsidian-indentation-guides It's unlikely that I'll add this to the theme since this exists

**Comment by SerosKanjus** [comment]
Since the newest update (0.14.2), obsidian now seems to force bullet point relationship lines, with no obvious way to turn them off. Will there be an option to turn them off within the theme? They rather ruin its clarity for me.
