### ISSUE TITLE
Where is the VilePlume colour scheme?

### ISSUE THREAD

**Issue by seatrout** [hungsu/typomagical-obsidian#2]
It's mentioned in the readme, but I can't see it in the style settings plugin (in light mode); and, though I love the typography, I would prefer a different colour scheme to Ruby Ficus. I appreciate that these things are very personal.

**Comment by hungsu** [comment]
Hi seatrout!

I've just added Vileplume now! It probably has some glitches, so if you spot anything do let me know and I'll try to fix as soon as I can.

I hear you on Ficus Ruby - I personally find myself using plain Obsidian colours most of the time, and bring Ficus Ruby in for fun at times. I set Ficus Ruby as a default to hopefully set myself apart from the other themes for Obsidian October, but more and more I'm thinking the value of Typomagical is the focus on typography than on popping colour.

Thank you again for the comment!

**Comment by seatrout** [comment]
Ah, thank you! I also prefer subdued, perhaps slightly yellowish colour schemes — light, but not pure white. At the moment I'm very happy with Sanctum's. But your typography is so elegant that I will certainly persist with this for two of my vaults.

**Comment by hungsu** [comment]
I agree with you - Vileplume was based on Nord and has a bit too much of its blueness, and could stand to be much warmer!

I'm excited to keep working on Typomagical and earn a place in your vault!

**Comment by seatrout** [comment]
I'm so old I still use Solarized for some things!

**Comment by hungsu** [comment]
Well now you've given me an idea

https://github.com/hungsu/typomagical-obsidian/issues/4
