### ISSUE TITLE
Feature request: Dataview support

### ISSUE THREAD

**Issue by Calorion** [hungsu/typomagical-obsidian#34]
Dataview is very very useful, but its data fields (say, [date:: 2012-05-30]) are ugly. I would like Typomagical to handle them to make them more attractive. The Minimal theme does this (not that that's how I want them to look).

**Comment by awsharif** [comment]
+1 for this.

**Comment by hungsu** [comment]
Hi @awsharif , @Calorion ,

Thanks for bumping, and thanks @Calorion for providing that code sample - I don't use dataview much and needed that.

I've uploaded a new version of Typomagical with a first version of styled dataview keys/values. Let me know what you think.

![image](https://user-images.githubusercontent.com/1990680/213359682-9095352c-c883-41c6-9754-fc135daa11f5.png)

**Comment by awsharif** [comment]
Thanks @hungsu for the quick turnaround. Much prefer it as it is now on light mode. I think the dark mode appears a little off, what do you think?

![image](https://user-images.githubusercontent.com/63009990/213364057-33d997a0-8d03-4670-b605-c47cf0b7df39.png)

**Comment by hungsu** [comment]
Ah that's quite ghastly! Pushed up another fix, please update. It's late for me but if you see anything else I'll take a look another day

![image](https://user-images.githubusercontent.com/1990680/213365886-d217be5c-d6e8-4fce-9b76-01748050fac9.png)
