### ISSUE TITLE
Feature Request: Better default Cyrillic typeface

### ISSUE THREAD

**Issue by SerosKanjus** [hungsu/typomagical-obsidian#42]
Typomagical looks wonderful with its serif typeface. However, the cyrillic typeface is notably lacking in comparison – being a much larger, and dissimilar, sans-serif. 
![image](https://user-images.githubusercontent.com/102552774/160478321-955463bc-21fb-4e72-ac5e-ecdb96002ba9.png)
This ends up making my documents, which often have a mix of both, look very disjointed. Much more appropriate cyrillic typefaces exist:
![image](https://user-images.githubusercontent.com/102552774/160478217-8ab4760b-ea02-4de1-a6cb-d7f36f5cc86d.png)

Pangram for checking fonts: Жълтата дюля беше щастлива, че пухът, който цъфна, замръзна като гьон

**Comment by SerosKanjus** [comment]
Regardless of the new possibilities potentially given by 0.14.3, it would be good for the default to be updated.

**Comment by hungsu** [comment]
Really appreciate the screenshots and sample text @SerosKanjus ! I'm at work but can fix this in a few hours perhaps

**Comment by hungsu** [comment]
Hi @SerosKanjus , sorry about the delay. I believe this is fixed in the body, and in headings if you are using Playfair Display. If it doesn't work, or you would like to use a different Heading font please let me know
