### ISSUE TITLE
"Show inline title" option in Obsidian 1.0 doesn't use Typomagical H1 style

### ISSUE THREAD

**Issue by Calorion** [hungsu/typomagical-obsidian#46]
In Reading view (though not, sadly, Live Preview), Typomagical displays H1s in a different font than the body. However, this does not apply to the new "Show inline title" option in Obsidian 1.0; it uses the body font.

**Comment by hungsu** [comment]
Hi Calorion! I don't use Obsidian's built-in inline title very much as I find mgmeyer's plugin to work better, but I can probably patch this today!

**Comment by Calorion** [comment]
That plugin has been removed from the Obsidian app store and archived, so it's built-in or nothing from now on, I'm afraid!

**Comment by Calorion** [comment]
*bump*

**Comment by hungsu** [comment]
Hi @Calorion , so sorry I forgot about this! I just pushed up a fix, if that doesn't resolve things for you please comment here again :)

**Comment by Calorion** [comment]
Obsidian doesn't seem to think there's an update available.

**Comment by hungsu** [comment]
Ah my mistake! Obsidian requires a change in the version number to realise an update's been made. You should be able to update now!
