### ISSUE TITLE
Typomagical doesn't respect accent color everywhere in dark mode

### ISSUE THREAD

**Issue by joelatschool** [hungsu/typomagical-obsidian#48]
While in light mode, the accent color is used everywhere in Typomagical (color of links, color of gradient on titles if enabled, UI, etc), in dark mode it seems to only use the accent color for UI, and links and gradients stay purple no matter what.

**Comment by hungsu** [comment]
Hi there, I'll see what I can do!

**Comment by awsharif** [comment]
I just noticed this - would be great to have consistency with accents in dark mode. Ps. I love the theme!

**Comment by hungsu** [comment]
Hi everyone - this should be fixed with the newest version of Typomagical, 1.7.3. If it isn't, please comment and I'll take another look
