### ISSUE TITLE
Theme does not apply to pop-out windows

### ISSUE THREAD

**Issue by philiplinden** [hungsu/typomagical-obsidian#55]
**Issue:** When additional windows of an Obsidian vault are opened, it uses the default theme instead of Typomagical.

**To Reproduce:**

1. Right click an open tab.
2. Select *Move to new window*
3. Observe that the new window uses the default Obsidian theme.

This happens in light or dark mode. It seems to be an issue with the theme, not Obsidian itself.

Inspecting [the commit that fixed this issue in the Things theme](https://github.com/colineckert/obsidian-things/commit/0a44cb39d146a3976c06e3b90a53d8befad42719), it looks like there were a bunch of lines where they removed `:not(.is-popout-window)` from `obsidian.css`. Unfortunately, it doesn't look like it will be so simple in Typomagical---I couldn't find anything matching "popout" in this repo.

**See also:** 

- https://forum.obsidian.md/t/new-window-but-keep-same-theme/40927/4
- https://github.com/colineckert/obsidian-things/issues/72#issuecomment-1229098537
- https://github.com/colineckert/obsidian-things/releases/tag/1.8.0

Love the theme! Wish I could be more helpful here

**Comment by hungsu** [comment]
Thanks for finding this @philiplinden ! As you may have guessed I rarely use this feature so it slippedunder my radar. It seems quite infuriating to resolve - the pop out windows seem to reject CSS that isn't to their liking, and doesn't say why. THe issue you linked was curious, and seemed to indicate that using `:not` selectors was something popouts didn't like, but that didn't seem to fix it for me. Resolving this issue looks like it will be a tedious exercise of me trying rules one at a time until I find the offender. Thank you for your patience!

**Comment by hungsu** [comment]
Well how about that, I believe I found it.

For any other Obsidian Theme developers who come through this way, the Obsidian pop out windows will not load CSS if you have a selector that uses special characters, such as `.ͼ1`

@philiplinden if you update the theme to 1.4.5 it should work now
