### ISSUE TITLE
Image magnification doesn't work

### ISSUE THREAD

**Issue by Smitty010** [hungsu/typomagical-obsidian#58]
Not sure if this is a bug or and enhancement.

In the Minimal theme, if I float the cursor over an image, the cursor changes to a magnifying glass and when I click on the image it displays a bigger view of that image.  I really like that feature.  

Doesn't happen with typomagical.

**Comment by hungsu** [comment]
This should now work as of version 1.7.0. If it still doesn't work please reopen this and I'll take a look
