### ISSUE TITLE
FR: Include sans serif SC font in link font menu

### ISSUE THREAD

**Issue by wpkelso** [hungsu/typomagical-obsidian#65]
It would be nice to have a sans serif link font option available in the Style Settings menu. Currently only Alegreya SC (serif), Spectral (serif), and Source Sans Pro (sans serif) are available, so for those of us who like the SC styling on links but prefer sans serif we're out of luck.

A couple recommendations I have of such fonts from Google fonts:
- Encode Sans SC
- Carrois Gothic SC

**Comment by hungsu** [comment]
Hi there @wpkelso ! I'm beginning to think about a sans body font option for Typomagical, and along with it a sans-serif SC for links as well! I will probably not use Encode Sans SC because the x-height is so high, but Carrois Gothic may have some promise. Thank you for the feature request!

**Comment by hungsu** [comment]
Hi @wpkelso , I currently am trialing Alegreya Sans SC as Typomagical's SC font, to pair with Alegreya Sans. This was added in a few days ago in Typomagical 1.9.0. I may try others, but i'm about 95% sure this is what I'll be sticking with. Let me know if you run into any issues!
