### ISSUE TITLE
Bug: Circled list numbers don't respect polymorphic list definitions

### ISSUE THREAD

**Issue by wpkelso** [hungsu/typomagical-obsidian#67]
Probably not a great title description, but essentially 
![image](https://github.com/hungsu/typomagical-obsidian/assets/11094688/8a3cb088-5864-4fa0-88b0-bc5be5ab0c41) creates ![image](https://github.com/hungsu/typomagical-obsidian/assets/11094688/62e62b84-6237-4084-bf90-8d8fa9446371) versus ![image](https://github.com/hungsu/typomagical-obsidian/assets/11094688/611b3bc7-4106-4abd-bc8a-19c3bfb98520)

It looks like it's applying the circled numbers indiscriminately to all members of the list, rather than *only* the numbered elements.

**Comment by hungsu** [comment]
Hi, thanks for reporting this! That's quite annoying but should be an easy fix

**Comment by hungsu** [comment]
This should be resolved with Typomagical 1.9.1

**Comment by wpkelso** [comment]
Yup, thanks!
