### ISSUE TITLE
Bug: Massive Space between a line and a formatted table.

### ISSUE THREAD

**Issue by WinnerWind** [hungsu/typomagical-obsidian#71]
![image](https://github.com/hungsu/typomagical-obsidian/assets/71366717/60f6ae53-0e38-49d7-bbc9-6038617ac5b1)
When making a table, it is necessary to leave a line between the last line, and the first line of the table. If this is not followed, the table will not format, as shown below.
![image](https://github.com/hungsu/typomagical-obsidian/assets/71366717/93b24bd7-0751-45ab-8382-ef5a55a0a1ea)
However, it seems that Typomagical is adding another gap between the ending of the last line and the starting of the table, even though this is unnecessary. (See first image)
For context, to generate the first image, here is how the source would have to look.
![image](https://github.com/hungsu/typomagical-obsidian/assets/71366717/4957ee66-447e-4f80-a88c-e19490c3134f)
This is not an issue with the default obsidian theme.
![image](https://github.com/hungsu/typomagical-obsidian/assets/71366717/69399948-faf8-45a9-a2e7-07de79b44554)
Is this an issue with the theme? 
Bonus : Bounding box of the table. Notice the extra gap between the box and the title.
![image](https://github.com/hungsu/typomagical-obsidian/assets/71366717/8879a8de-fa7a-4378-9572-6c4c62225046)

**Comment by hungsu** [comment]
This was an old decision - I always wanted space between text and tables. Users can just manually add empty lines themselves so this has been removed.
