### ISSUE TITLE
Bug: custom fonts does not work

### ISSUE THREAD

**Issue by bluebirch** [hungsu/typomagical-obsidian#72]
Until the other day the Typomagical theme worked as expected. Now, for some reason, the body text font is not set. This happens also in a Sandbox vault.

<img width="1136" alt="Screenshot 2023-12-31 at 10 50 29" src="https://github.com/hungsu/typomagical-obsidian/assets/4832639/6d2a2d74-7667-49a7-b2aa-ad384a24f103">

Fonts for links works, but not the body text.

**Comment by hungsu** [comment]
Hi @bluebirch , I see you're on MacOS, what version of Obsidian are you using?

**Comment by bluebirch** [comment]
> Hi @bluebirch , I see you're on MacOS, what version of Obsidian are you using?

I'm using 1.5.3.

**Comment by hungsu** [comment]
Thank you. This appears to be the same issue as #68 , which is partially fixed. I'll check in on you again when that issue closes

**Comment by hungsu** [comment]
@bluebirch can you check if Typomagical 1.9.5 resolves the issue for you?

**Comment by bluebirch** [comment]
> can you check if Typomagical 1.9.5 resolves the issue for you?

It does. Thank you!
