### ISSUE TITLE
Bring Amiri and weighting back

### ISSUE THREAD

**Issue by ndharari** [hungsu/typomagical-obsidian#73]
Yes I am going to be that guy. I dont care if I have to install the font locally. Please!

**Comment by ndharari** [comment]
Love your theme btw, it looks soooo good.

**Comment by hungsu** [comment]
Glad you like the theme and thanks for bringing this up! I sadly had to be cautious with embedding fonts, because the theme with all the current fonts is already kind of absurdly sized at 1.5MB - that's mostly fonts! 

But something I could maybe do is add an open text field for users to specify the name of their own desired font for titles and leave it to them to install font. Similarly I could put the slider back in for font weights: it just wouldn't work correctly unless the font weights were installed

**Comment by ndharari** [comment]
A small price to pay if you ask me! There's no theme that has such an exportable look as typomagical with font weight at 500 😉

**Comment by hungsu** [comment]
@ndharari , were you using Spectral or Alegreya Sans at 500? And what weight were you using for bold?

**Comment by ndharari** [comment]
Sorry for the delay. I was using Spectral at 500 but right now I see no changes when I set the body text weight below 600. 
Anything below 600 looks the same, and everyhing over 600 looks like everything is bold. 
Same thing happens for bold text weight

**Comment by hungsu** [comment]
I've added 500 weight back for now, so that 400, 500 and 700 are available.

**Comment by ndharari** [comment]
Can we have also our nice heading with amiri please???🥺

You are the best!

**Comment by ggneilc** [comment]
bump on bringing back amiri font (I also do not care if I have to local install), I started using typomagical theme and obsidian to export my homework pdfs and the amount of compliments I get from TA feedback is insane and I can't let that be taken away halfway through the semester.

**Comment by hungsu** [comment]
Note to self from kepano:

> as of Obsidian 1.5 Google Fonts are the only external URLs that are allowed — but in general it's best to embed your fonts using base64 so that they are available locally 
> for Google Fonts you must use the fonts.googleapis.com URL 

This means I can skip base64 encoding Amiri, and include it just as a google font

**Comment by hungsu** [comment]
Amiri is back with 2.0.3. Requires an internet connection as before

Spectral and Alegreya Sans weights still need to be put back

**Comment by hungsu** [comment]
@ggneilc , so sorry I forgot to reply to you directly! thank you so much for your lovely message. It didn't occur to me to use Typomagical in exported PDFs, but I can see how that would work!

**Comment by hungsu** [comment]
This is resolved. Thank you all for enjoying Typomagical!
