### ISSUE TITLE
Bug:Bold font is not displayed correctly in edit mode

### ISSUE THREAD

**Issue by MrSitnikov** [hungsu/typomagical-obsidian#74]
Bold font is not displayed correctly in edit mode. I have not seen this problem before.
![bold1](https://github.com/hungsu/typomagical-obsidian/assets/47792968/1da37e8c-7924-4b43-851b-7ae027cb202d)
![bold2](https://github.com/hungsu/typomagical-obsidian/assets/47792968/6b295e15-2baa-442d-8183-aa1b51ec711b)
![bold3](https://github.com/hungsu/typomagical-obsidian/assets/47792968/54b2ec87-4e14-4f1f-a034-31780045dcfc)

**Comment by MrSitnikov** [comment]
The backlight began to appear gray, previously it was green.
![image](https://github.com/hungsu/typomagical-obsidian/assets/47792968/b2601619-ee1a-4878-918c-39e8e8286f59)

**Comment by hungsu** [comment]
Hi @MrSitnikov , thank you for your bug report!. I've identified the cause of bold not being bold. It's because of an assumption I made with Style Settings. Please download Typomagical 2.0.8 to see that fixed

**Comment by hungsu** [comment]
Regarding your code formatting problem, it is a mystery, I'm not able to reproduce it. What I see is below:
![image](https://github.com/hungsu/typomagical-obsidian/assets/1990680/57274326-d1ea-4509-a243-603938dfe7bc)

Can you please supply as much of the following as you can:
- list of enabled obsidian plugins you are using, if any
- list of enabled CSS snippets you're using, if any
- operating system you are on
- your Obsidian version

**Comment by MrSitnikov** [comment]
I'm sorry, after reinstalling everything started working correctly.
